[package]
name = "ps-cypher"
version = "0.1.0-28"
edition = "2021"
description = "Chacha-based data cypher"
license = "GPL-3.0-or-later"

[dependencies]
chacha20poly1305 = "0.11.0"
ps-base64 = "0.1.0-7"
ps-buffer = "0.1.0-22"
ps-compress = "0.1.0-18"
ps-ecc = "0.1.0-9"
ps-hash = "0.1.0-25"
ps-pint16 = "0.1.0-5"
ps-util = "0.1.0-9"
thiserror = "2.0.20"

[lints.clippy]
expect_used = "deny"
nursery = { level = "warn", priority = -1 }
panic = "deny"
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"

[lints.rust]
unsafe_code = "forbid"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
